### ISSUE TITLE
Mini-modèle numérique NGC/MCCO2

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat-site#656]
## MCCO2 x NGC : publicodes

Quel est le format actuel des données MCCO2 ? 

(il est en JSON, je l'ai transcrit en YAML)
```yaml
name: Bouilloire[s]
slug: bouilloire
emoji: ⚗️
category: 6
ecv:
  - value: 3.92551745975495
    id: 1
  - value: 0.236818204229257
    id: 2
  - value: 0.590293393621879
    id: 3
  - value: 4.98051969151672
    id: 4
usage:
  peryear: 5.27273319
  defaultyears: 6
end: -0.659363081745786
default: false
tile: false
meta:
  title: Impact sur le climat d'une bouilloire
  description: >-
    Avec Mon Convertisseur CO2, découvrez l'impact sur le climat d'une
    bouilloire, avec son poids en CO₂e comprenant sa fabrication et sa
    distribution.
source: >-
  https://librairie.ademe.fr/dechets-economie-circulaire/127-modelisation-et-evaluation-environnementale-de-produits-de-consommation-et-biens-d-equipement.html
```
On observe une grande similarité dans les meta (title, description, emoji, catégorie gérée dans publicodes via l'espace de nom imbriqué). 

Quand aux données, voilà comment ça pourrait être encodé : 

```yaml


```

Quelles fonctionnalités manquantes dans publicodes dont a besoin MCCO2 ? 

Comment encoder dans publicodes la répartition en cycle de vie ? 

Utiliser les composantes ? Dans ce format ou dans un format évolué. 
https://publi.codes/docs/mécanismes/#composantes

## Tester la convergence sur le modèle numérique

Il est très calculatoire, donc assez adapté pour publicodes. 

C'est un tableur de type modèle de calcul plutôt que CSV. 

On pourrait intégrer le modèle numérique dans nosgestesclimat, ce qui le rendra disponible sur nosgestesclimat.fr/documentation, et en parallèle donner accès au modèle numérique via une API en ligne (du genre co2.fr/api/numérique/requête-web?temps-utilisation=45min) qui permettrait à monconvertisseurco2.fr d'utiliser publicodes sans charger publicodes-core, ce qui est un peu trop pour en sortir qu'une variable (contrairement au bilan entier de NGC).

- [ ] ébaucher le modèle numérique en publicodes, sur nosgestesclimat ? 
- [ ] réfléchir à la séparation des domaines sur nosgestesclimat pour pas trop alourdir l'ensemble
- [ ] tester la fonction API de publicodes
- [ ] l'utiliser dans monconvertisseurco2
