### ISSUE TITLE
définition de variable sur la base d'une réponse à une question donnée

### ISSUE THREAD

**Issue by simogeo** [datagir/nosgestesclimat-site#977]
C'est encore moi ...

Je souhaite moduler le résultat d'une question dans une catégorie donnée par le résultat d'une autre question. Pour prendre un exemple concret, ce qui semble faisable. 

A titre d'exemple, je peux, déclarer `logement . facteurSP: 0.3` dans _logement.yaml_ et appeler la formule suivante dans _services public.yaml_ : 

`formule: 999 * logement . facteurSP`

Mais je souhaiterai que cette variable `logement . facteurSP` change de valeur en fonction de la réponse donnée à une précédente question ? Est-ce jouable ? Est-ce la bonne approche et si oui comment faire ?

Puis-je par exemple la liée à [cette question](https://github.com/datagir/nosgestesclimat-site/issues/975) et faire en sorte que si la réponse est Tahiti `logement . facteurSP`  prenne la valeur 1 si  Autrales `logement . facteurSP`   prenne la valeur 0.7, ...

Ou dois-je faire le test dans _services public.yaml_  avec une syntaxe du type : 

```
  formule:
    variations:
      - si: logement . résidence . archipel = 'Tahiti'
        alors: 999 * 1
      - si: logement . résidence . archipel = 'Autrales'
        alors: 999 * 0.7
```

J'ai testé cette deuxième solution qui fonctionne. La première est-elle envisageable ? je veux bien savoir ce qui est préférable ! Merci de votre éclairage ?
